const db = require("./connection");

const { Dog, Breed, Color, Status, Temperament, User } = require("../models");

db.once("open", async () => {
    await Color.deleteMany();
    const color = await Color.insertMany([
        { name: "Brown" },
        { name: "Red" },
        { name: "Gold" },
        { name: "Cream" },
        { name: "Fawn" },
        { name: "Black" },
        { name: "Blue" },
        { name: "White" },
        { name: "Orange" },
        { name: "Silver" },
        { name: "Tan" },
        { name: "Grey" },
    ]);
    await Temperament.deleteMany();
    const temperament = await Temperament.insertMany([
        { name: "Active" },
        { name: "Adaptable" },
        { name: "Affectionate" },
        { name: "Aggressive" },
        { name: "Agile" },
        { name: "Alert" },
        { name: "Aloof" },
        { name: "Amiable" },
        { name: "Athletic" },
        { name: "Attentive" },
        { name: "Boisterous" },
        { name: "Bold" },
        { name: "Brave" },
        { name: "Bright" },
        { name: "Calm" },
        { name: "Cautious" },
        { name: "Charming" },
        { name: "Cheerful" },
        { name: "Clever" },
        { name: "Clownish" },
        { name: "Courageous" },
        { name: "Confident" },
        { name: "Cooperative" },
        { name: "Curious" },
        { name: "Determined" },
        { name: "Devoted" },
        { name: "Dignified" },
        { name: "Docile" },
        { name: "Easygoing" },
        { name: "Energetic" },
        { name: "Even Tempered" },
        { name: "Excitable" },
        { name: "Extroverted" },
        { name: "Faithful" },
        { name: "Fearless" },
        { name: "Friendly" },
        { name: "Generous" },
        { name: "Gentle" },
        { name: "Good-natured" },
        { name: "Gregarious" },
        { name: "Happy" },
        { name: "Independent" },
        { name: "Instinctual" },
        { name: "Intelligent" },
        { name: "Keen" },
        { name: "Kind" },
        { name: "Lively" },
        { name: "Loyal" },
        { name: "Loving" },
        { name: "Mischievous" },
        { name: "Obedient" },
        { name: "Opinionated" },
        { name: "Outgoing" },
        { name: "Patient" },
        { name: "Playful" },
        { name: "Powerful" },
        { name: "Protective" },
        { name: "Quick" },
        { name: "Quiet" },
        { name: "Reliable" },
        { name: "Reserved" },
        { name: "Responsive" },
        { name: "Self-assured" },
        { name: "Sensitive" },
        { name: "Sociable" },
        { name: "Spunky" },
        { name: "Steady" },
        { name: "Strong" },
        { name: "Stubborn" },
        { name: "Suspicious" },
        { name: "Sweet-Tempered" },
        { name: "Tenacious" },
        { name: "Thoughtful" },
        { name: "Trainable" },
        { name: "Trustworthy" },
        { name: "Vocal" },
        { name: "Watchful" },
        { name: "Willful" },
    ]);
    await Breed.deleteMany();

    const breed = await Breed.insertMany([
        { name: "German Shepard", minLife: 8, maxLife: 10, hypoallergenic: false, colors:[color[5], color[9], color[10], color[11]], temperaments:[temperament[5],temperament[20],temperament[21],temperament[23],temperament[43],temperament[47],temperament[50],temperament[76]] },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: false, colors:[color[7],color[4],color[1],] },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Bulldog", minLife: 8, maxLife: 10, hypoallergenic: },
        { name: "Jack Russell Terrier", minLife: 13, maxLife: 16, hypoallergenic: false },
        { name: "Curly-coated retriever", minLife: 9, maxLife: 14, hypoallergenic: false },
        { name: "Afghan Hound", minLife: 12, maxLife: 14, hypoallergenic: true },
        { name: "American Eskimo", minLife: 13, maxLife: 15, hypoallergenic: false },
        { name: "Sheltie", minLife: 12, maxLife: 13 hypoallergenic: false },
        { name: "Airedale Terrier", minLife: 10, maxLife: 12, hypoallergenic: true },
        { name: "Bull Terrier", minLife: 10, maxLife: 14, hypoallergenic: false },
        { name: "Irish Wolfhound", minLife: 6, maxLife: 10, hypoallergenic: false },
    ])
})